### ISSUE TITLE
Add extra step for token verification in email authentication

### ISSUE THREAD

**Issue by franciclo** [iaincollins/next-auth#10]
This is more of a feature request than an issue if we don't mind the possibility of automatic signins, i would like to use a recaptcha to prevent this.
One way could be instead of checking the token right away after user clicks the link in the email, it could be forwarded to a page where a recaptcha could verify its not a bot and then perform the token checking via ajax, i assume the recaptcha validation is only needed for the email authentication not for the identity providers, this way only the email authentication flow gets validated by recaptcha.
This page could also set the token in localstorage triggering the 'storage' event letting the other open tab know the user is now logged and sync.
(Sorry if last part is unrelated, i think this package is amazing, thanks btw)

**Comment by iaincollins** [comment]
Hi there,

These are good request and there is certainly need for better email token handling (specifically, I've been meaning to add an expiry timestamp).

Perhaps the best place for captcha with next-auth is possibly on signing up via email, to prevent account creation by bots (before an account and token is even generated).

A good place to put this might be in the [nextjs-starter](https://nextjs-starter.now.sh) project - I will look at adding reCAPTCHA to it (and also write it up on the wiki here). If I can keep it simple and small I'l also include it directly next-auth example too. I'd be very happy to include helper functionality in next-auth and next-auth-client if it makes it easier and makes sense to have there though, as I agree it's something to encourage people to implement.

Having the next-auth-client trigger updating of other tabs is definitely a thing I'd like to have but requires some thought and I'm not sure if there is a really good way to do it that would work for everyone yet.

Currently session state is reflected next time you load a page in an old tab (because as soon as you load a page, it sees the new cached session state in localStorage and sees that the user is now logged in), but it would be nice to be able to update pages immediately.

The problem with doing that is - even if we used a store instead of just props to access session state, so could update the state of them dynamically  - pages render differently when you are logged in and not logged in. Often it's small things in the UI (like navbar contents) but sometimes it's more complex behaviour, like rendering different form options when a user is logged in. I wouldn't want to force re-rendering of the current page as data might be lost (e.g. the contents of form fields, or unsaved app state).

Perhaps a good approach is to fire an event people can bind to, or even to reload pages by default when signed in/signed out in another tab, but let people pass an option to specific pages to disable the automatic reloading behaviour and/or handle it manually.

**Comment by franciclo** [comment]
I agree, the captcha should be placed before account and token creation, i was thinking how zeit site might work. 
I think i could place the captcha in singin page or load it after email submit click, an example of how to implement it would be cool, thanks.

I was looking for options of how to make tabs update but as you say is hard to find one with full browser support, i think the best way would be done all in the browser (no websockets) and even though im not very familiar with web workers it seems like the way to go. In the other hand, the most supported option i found would be using `localStorage` and the "storage" event, using `local-storage` package that brings better support as stated in [this blog post](https://ponyfoo.com/articles/cross-tab-communication).

**Comment by iaincollins** [comment]
Thanks for the feedback and suggestions. Am going to leave this one open and work on it.

I think using the storage API is a really great way to listen for / fire an an event across tabs and seems like the best way to make it easier to do live updating when session states change.

Maybe a good way to start would be if I made it easy to listen to session changes in pages by adding an easy hook in the `next-auth/client` to handle either the opt-in or opt-out automatic page reload behaviour.

A future release, maybe something to save for 2.0, could refactor to use a store for session changes, to make it easier to handle gracefully in more situations.

**Comment by iaincollins** [comment]
While it doesn't *exactly* address this issue, for anyone reading who is interested in this as of 1.8.0 you can now define a custom signIn() function - and optionally disable the built in email token system - and write your own function to handle sign in form submission as a way of doing this.

Like the other sign in methods it works with and without JavaScript in the client, and you can handle processing any request you like. An example signIn() function and example page showing how to use it is provided.

**Comment by iaincollins** [comment]
The new features in 2.0, which include custom `signin()` callbacks, Credentials Provider and fully customisable emails, custom sign in pages address the issue raised in this ticket.

Additionally, Users accounts are no longer created until *after* an email sign in email has been activated, and tokens are stored more securely in the database, to prevent abuse.
