### ISSUE TITLE
Side effect of using custom server

### ISSUE THREAD

**Issue by tanvp112** [iaincollins/next-auth#101]
Hi there,

Sorry, I noticed that I have not changed the branch to next-auth-2; which if not mistaken is not a custom server like 1.x and therefore will not have the side effect of [remove automatic static optimization](https://nextjs.org/docs/advanced-features/custom-server), correct?

Thanks!

**Comment by iaincollins** [comment]
Hi @tanvp112,

Absolutely, that is correct yes! 

### How this works

In order to avoid impacting automatic static optimisation of pages in NextAuth 2.0 , the trade off is that when calling `NextAuth.session()` to do server side authentication in  `getInitialProps()` or `getServerSideProps()` then it will use `fetch()` request to `/api/auth/session` (as if it was a browser), using the session ID token extracted from HTTP headers.

To facilitate keeping it it zero-configuration in clients, the base URL for authentication requests is set securely in a cookie by the server on first request (e.g. `__Secure-next-auth.url-prefix=https://next-auth/api/auth`), this cookie then read by server side route to determine the URL to use to validate the session. For security, this cookie is signed with a verification token (a hash generated with a secret salt) that is checked on every request.

For most use cases, the client side `useSession()` hook will probably what folks want:

```javascript
import NextAuth from 'next-auth/client'

export default () => {
  const [session, loading] = NextAuth.useSession()

  return <>
    {!loading && session && <p>Signed in as {session.user.name || session.user.email}.</p>}
    {!loading && !session && <p>Not signed in.</p>}
  </>
}
```

This hook currently verifies the session on every request (via an async call, so non-blocking) but in future it use local storage to cache data on the client when navigating between pages (as NextAuth 1.x does), so that the session object is always available immediately in the client.

**Comment by iaincollins** [comment]
Going to mark this as resolved, but do re-open if you have any follow up questions!
