### ISSUE TITLE
[v2] add Twitch provider

### ISSUE THREAD

**Issue by LoriKarikari** [iaincollins/next-auth#102]
This is the configuration for Twitch. Tested by adding a custom object to the Providers list.
```
{
      id: 'twitch',
      name: 'Twitch',
      type: 'oauth',
      version: '2.0',
      scope: 'user:read:email',
      options: { grant_type: 'authorization_code' },
      accessTokenUrl: 'https://id.twitch.tv/oauth2/token',
      authorizationUrl:
        'https://id.twitch.tv/oauth2/authorize?response_type=code',
      profileUrl: 'https://api.twitch.tv/helix/users',
      profile: profile => {
        const data = profile.data[0];
        return {
          id: data.id,
          name: data.display_name,
          image: data.profile_image_url,
          email: data.email,
        };
      },
     ...options
    },
```

**Comment by iaincollins** [comment]
Thank you! This is really appreciated

**Comment by iaincollins** [comment]
Added Twitch to the example at http://next-auth-example.now.sh which is now on GitHub.

Thanks again, this works great!

**Comment by LoriKarikari** [comment]
Nice! I can add some other providers too if you want.

**Comment by iaincollins** [comment]
Oh yes please, that would be really neato! Thanks for all your help so far!

If you run into any you can't get working but you *think* they have the correct details, I'm really happy to get PRs for them too, if you can leave a comment in to say they might be not working yet.

I can try them with a different oAuth library and see if that is a quick fix; it's possible some providers won't work well with all oAuth libraries.

I need to add Facebook at some point, but I didn't add it at the start because it doesn't work with callbacks at localhost URLs (at least that used to be the case, not sure if it's still true). Other than that it was fine, it was just more awkward to test locally.
