### ISSUE TITLE
Add option for database collection prefix

### ISSUE THREAD

**Issue by ericvrp** [iaincollins/next-auth#140]
I am using mongodb. There are 4 collections created (account,email_verification,session and user). Is there an option where I set the prefix for all NextAuth collections/tables to something like nextauth_account, nextauth_email_verification.... ?

**Comment by iaincollins** [comment]
Absolutely! I want this feature in too, thanks for raising it.

This is a lot safer default behaviour, and should be able to make it easy to customise.

It would also make it easier it easier to do things like use a single database as a service instance to host multiple sites, which is great for prototyping / smaller projects.

**Comment by iaincollins** [comment]
Happy say I did some digging and it turns out this is already supported, thanks to the `entityPrefix` option in TypeORM!

You can specify a prefix  using a connection string or as an option on a configuration object:

```javascript
database: `mysql://nextauth:password@127.0.0.1:3306/nextauth?synchronize=true&entityPrefix=nextauth_`
```

```javascript
database: {
  type: 'mysql',
  host: "127.0.0.1",
  port: 3306,
  username: 'nextauth',
  password: 'password',
  database: 'nextauth',
  entityPrefix: 'nextauth_',
  synchronize: true
}
```

I've confirmed it as working for both SQL databases and for MongoDB.

## MySQL 
![Screenshot 2020-05-26 at 19 28 55](https://user-images.githubusercontent.com/595695/82937345-ea635080-9f87-11ea-839d-e932482c234e.png)

## MongoDB
![Screenshot 2020-05-26 at 19 33 50](https://user-images.githubusercontent.com/595695/82937349-ec2d1400-9f87-11ea-91b1-6120d65cfddb.png)

I am leaning towards not making this the default, but am very open to people changing my mind on that if there is particularly strong feeling one way or another.

It is probably worth drawing attention to this option in the NextAuth.js documentation either way though.
