### ISSUE TITLE
Sqlite account table providerAccountId get stored as decimal value  or  truncating

### ISSUE THREAD

**Issue by im-sunil** [iaincollins/next-auth#148]
providerAccountId: '4517376869.0'
or 
providerAccountId: '1.26207928514727e+18',
![image](https://user-images.githubusercontent.com/6269292/82675414-6563f880-9c62-11ea-984a-c3af128f86a6.png)

**Comment by iaincollins** [comment]
Thanks for raising this. The data type on the model looks right (varchar), I wonder if it's a stupid sqlite thing. Will investigate!

**Comment by iaincollins** [comment]
I've tried to replicate with a range of Twitter accounts, but I'm not seeing this issue in the current release, so I'm going to close this issue.

However, if you are still seeing it, I'm happy if you'd like to reopen it - in fact I'd appreciate it if you did, as I'd rather know if it's an ongoing issue.

If that's the case, please let me know what version of SQLite you are using and what platform you are using (e.g. Windows, Mac, Ubuntu, Debian, etc) so that we can replicate.

I would also be interested to know if you see the same thing using any of the other supported databases (MySQL, Postgres, MongoDB) now that they should all be working.
