### ISSUE TITLE
Session question including provider accessToken

### ISSUE THREAD

**Issue by geraldnolan** [iaincollins/next-auth#179]
What are your thoughts on including something like this in the session object?  

in session.js

```javascript
const user = await getUser(session.userId)
const accounts = await getAccounts(session.userId);

        let providers = {}
      
        accounts.forEach(account => {
          providers[account.providerId] = {
            ...providers,
            accessToken: account.accessToken,
          }
        })

        // Only expose a limited subset of information to the client as needed
        // for presentation purposes (e.g. "you are logged in as…").
        //
        // @TODO Should support `async seralizeUser({ user, function })` style
        // middleware function to allow response to be customized.
        response = {
          user: {
            name: user.name,
            email: user.email,
            image: user.image
          },
          accessToken: session.accessToken,
          expires: session.sessionExpires,
          providers: providers
        }

``

**Comment by iaincollins** [comment]
Hey great question! Someone actually asked about that recently.

To support this without adding too much to the current session object, I've been planning endpoints similar to v1, to return linked accounts - and to explicitly link/unlink. 

## Example routes

 * GET /api/auth/accounts – Return JSON object (as above) for current user 

* GET /api/auth/link – Basically same as sign in page, but different wording on buttons
  (e.g. would support routes like POST `/api/auth/link/google` to link) 

* GET /api/auth/unlink – Basically same as sign in page, but different wording on buttons
  (e.g. would support routes like POST `/api/authunlink/google` to unlink) 

NB: These pages would all require a user to already be signed in with a valid session.

I was planning on account linking in 2.1, to keep scope of 2.0 down. There isn't an issue to track this yet though! Would welcome any assistance here.

**Comment by geraldnolan** [comment]
@iaincollins My use case may be different than most where I already have an identity provider that supports SSO and issues a JWT. I will only have one provider/maybe two, and the front end micro-service (next js) needs to talk to the ambassador API gateway. I thought maybe it makes sense to add an attribute to the provider that it allows it to come down in the session object. The session object would be small, which would not require another API call. I am happy to elaborate a little more on the use case if I need to.

```javascript
 Providers.IdentityProvider({
      clientId: IDENTITYPROVIDER_ID,
      clientSecret: IDENTITYPROVIDER_SECRET,
      clientProviderAccessToken: true
    }),

```

I have been working on the **/api/auth/refresh-token/provider** endpoint. (Which should be ready soon)

**Comment by iaincollins** [comment]
Hmm I think probably adding support for a custom function as an option to NextAuth when creating the API route is probably the way to go for folks who want this in the session object, rather than adding an option to each provider.

That would give a lot of flexibility (for regular sessions and for JWT) with a single approach that should work for a lot of folks.  It sounds like the `/api/auth/accounts` endpoint would also meet this need for most people too. The plan is to add being able to specify middleware functions for `signin` and `signout` as well as `session`, so the convention would be easy to follow and consistent.

I envisage `/api/auth/accounts`  returning a list of all linked providers, each with access tokens and expiry times (and ultimately handling using the RefreshToken for each service to update the AccessToken for it when it expires).

There would  be a `NextAuth.accounts()` in the client to call this endpoint (the similar function in v1 was called `linked()`).

I am not sure I'd want to create something that exposed a RefreshToken to the front end though, I would probably not accept a patch for that as I don't want to create a footgun in a library that's intended to lower the barrier to adding authentication (but of course folks could create their own API endpoints that look up the session object and do that).

I'm interested to here more about the use case though.

**Comment by geraldnolan** [comment]
@iaincollins  Thanks for taking the time to elaborate on your design.  Maybe it makes sense to jump on a call next week?  I like to help you push this project forward.

Can you give this code a glance? Provide any comments that you would change.

[https://github.com/geraldnolan/next-auth/commit/d4c8f7cd03886f715814ec2bd7b8a334a160b647](https://github.com/geraldnolan/next-auth/commit/d4c8f7cd03886f715814ec2bd7b8a334a160b647)

I thought it would be nice to have comments in the DB based on the model, but I don't think that's an option of TypeORM, so I thought the next best thing is to put them in code?

** I haven't tested the softDelete on the user but I think it would be a nice feature.

**Comment by iaincollins** [comment]
A call would be great! I'm pretty busy during the day, but am free most days after 5 PM GMT (6PM BST, 7PM CEST), or at weekends. Feel free to reach out at **me@iaincollins.com**

Many thanks for your help in testing things out and reporting issues with recent changes!
