### ISSUE TITLE
Mongodb does not work with Email auth

### ISSUE THREAD

**Issue by MatthieuCoelho** [iaincollins/next-auth#198]
Hello,
Thanks for this great library, I'm on version 2.0.0-beta.59 and it seems like Mongodb does not work with Email auth.

After clicking on the link being sent by email I get this error :
`EMAIL_CALLBACK_ERROR TypeError: Cannot read property 'id' of undefined
    at next-auth/dist/server/lib/callback-handler.js:1:1381
`
It seems related to this line,
https://github.com/iaincollins/next-auth/blob/50b9743bb6a659c6b3061f07b7f5db1ede00ff04/src/server/lib/callback-handler.js#L68

Shouldn't it be "user._id" when the database is mongodb ?

**Comment by iaincollins** [comment]
Thank you for the bug report!

So, the methods in the default database adapter *should* be handling that abstraction, but I've worked out what is going on.

I'm going to guess you have `jwt` enabled with `mongodb` and that this is happening when you are trying to sign in while already having a valid session.

When using a JWT the User ID is extracted from the token, rather than from a query to the session table, this means it's `type` is not an ObjectID but a string. When `getUser` was being called, it was failing because it was a regular string and looking up an ObjectID with a string does match.

There were a couple of other related issues which compounded this error, including the order of conditional checks not being very good and another almost identical problem when it ties to link accounts which is in turn a consequence of the sign in page not currently checking to see if you are already signed in (which is intended oddity for now, as account linking isn't complete yet).

To top that off, documentation was also wrong and should have listed `npm i mongodb` as the driver install instructions for MongoDB.

I've just published a fix as `2.0.0-beta.60` and would appreciate your feedback!
