### ISSUE TITLE
Get all the session data in an API route?

### ISSUE THREAD

**Issue by n3oney** [iaincollins/next-auth#206]
Hi. So using [session({ req })](https://next-auth.js.org/getting-started/client#session-req-) only gives you the following data:
```
{
  user: {
    name: string,
    email: string,
    image: uri
  },
  accessToken: string,
  expires: "YYYY-MM-DDTHH:mm:ss.SSSZ"
}
```
Is there a way to get all the user data in an API route?

**Comment by iaincollins** [comment]
Hey there! 

So I just put out an update to the documentation to explain this a little better.

If you check out that page you should see an example with `accessToken`.

The rather unsatisfying but perhaps simplest answer right now is, you can use that `accessToken` to look up the session in the session database and get the `userId` from the corresponding row.

However, you will need to handle doing that yourself right now.

Note: Alternatively, if you are using JWT for sessions - instead of a database - then you can read and decode the session from the `sessionToken` cookie. This is also not a very satisfying answer as it is not documented.

In future, it would be easier if we exposed a simple server side function that can do this securely so it was easier to get info from an API route, but there isn't a function that does this yet.

**Comment by n3oney** [comment]
So... that does not work well.
```
const s = await session({ req });
console.log(s.accessToken.length); // 64
```
Meanwhile, in the database (postgres), the length of accessToken in `entityPrefix`_account is 30. I'm not sure if I'm checking for the right things.

**Comment by n3oney** [comment]
Maybe because of `jwt: true` in my configuration.

**Comment by iaincollins** [comment]
Ah! The `accessToken` returned in `session` is the one in the *session* table!

Not the OAuth account access token (which is what in the account table).

**Comment by iaincollins** [comment]
Take a look at #212 for an example of how to decode a JWT in the current beta.

You might want to track #215 as this is about to change (and get a lot easier) soon.

**Comment by n3oney** [comment]
Is getting the `userId `from `session`, and then getting the rest of the data from `account` by the `userId` a safe approach?

**Comment by n3oney** [comment]
I've stopped using JWT and the following code is working for me now:
```ts
const s = await session({ req });
    const user = (await db.query(`SELECT "providerAccountId" FROM auth_account WHERE "userId" IN (SELECT "userId" FROM auth_session WHERE "accessToken"=$1)`, [s.accessToken])).rows[0];
```

**Comment by iaincollins** [comment]
> Is getting the `userId `from `session`, and then getting the rest of the data from `account` by the `userId` a safe approach?

Absolutely, that's ideal!

There is no fancy or joining or relations by default so as to keep the default database adapter as compatible with as many databases as possible (e.g. both SQL and NoSQL), but that is the intended use. Hopefully we can provide some tutorials / examples in future.

Getting info from JWT should get easier soon (new methods being worked on as part of #215) and you should be able to combine the approach above with JWT very easily if you want to go back to using JWT sessions later (in the case of JWT the userID is in the token, but otherwise the same approach would work).

**Comment by n3oney** [comment]
Thank you! Website is working! https://neoney.xyz https://neoney.xyz/api/auth/login/discord
The actual API route is used to send ban appeals to a Discord server, and it makes sure the user is banned before sending it, so I doubt you will find a way to use it, but the top bar shows the user info, and you can click it to sign out

**Comment by iaincollins** [comment]
Going to close this now, but would note for @n3oney that in v2.2 we had to change this slightly as it wasn't working reliably.

To get a session in an API route reliably, you may have to use the undocumented feature `setOptions()`.

```js
import { setOptions, getSession } from 'next-auth/client'
setOptions({ site: process.env.SITE })

export default async (req, res) =>  {
  const session = await getSession({ req })
  console.log('session', session)
  res.end()
}
```

This was added to fix the problem of how to get session data reliably in an API route, but we are still thinking of a better approach, so this is an "unsupported workaround" for now but should be helpful to anyone who needs it.

If using JWT for sessions it's a bit easier and you can use the `getJwt()` call which is supported and I don't expect to change:

```js
import jwt from 'next-auth/jwt'

const secret = process.env.JWT_SECRET

export default async (req, res) =>  {
  const token = await jwt.getJwt({ req, secret })
  res.end(JSON.stringify(token, null, 2))
}
```
