### ISSUE TITLE
How does database migration work?

### ISSUE THREAD

**Issue by adarnon** [iaincollins/next-auth#240]
I couldn't find a way to manage a production DB. The `?synchronize=true` option is OK for development, but obviously it is risky in production settings.
Is there some way to generate migrations so that I can configure a production database before deploying my app?

**Comment by lnikell** [comment]
Thank you for the great product @iaincollins. Had the same issue today, that were not able to find documented tables definition, so I ran synchronize=true at first and then converted it into migrations. 
From the structure I see now there are no indexes/fk that have set during initialization of DB data. I'm looking on it there https://github.com/iaincollins/next-auth/blob/master/src/adapters/typeorm/models/account.js. Also should be a good thing to improve

Definitely upvote for changing the current approach from auto sync to migrations.
And for those who probably will need table structure:
verification_request table:
```sql
-- Sequence and defined type
CREATE SEQUENCE IF NOT EXISTS verification_request_id_seq;

-- Table Definition
CREATE TABLE "public"."verification_request" (
    "id" int4 NOT NULL DEFAULT nextval('verification_request_id_seq'::regclass),
    "identifer" text NOT NULL,
    "token" varchar NOT NULL,
    "expires" timestamp NOT NULL,
    "created" timestamp NOT NULL,
    PRIMARY KEY ("id")
);
```
account table:
```sql
-- Sequence and defined type
CREATE SEQUENCE IF NOT EXISTS account_id_seq;

-- Table Definition
CREATE TABLE "public"."account" (
    "id" int4 NOT NULL DEFAULT nextval('account_id_seq'::regclass),
    "compoundId" varchar NOT NULL,
    "userId" int4 NOT NULL,
    "providerId" varchar NOT NULL,
    "providerType" varchar NOT NULL,
    "providerAccountId" varchar NOT NULL,
    "refreshToken" text,
    "accessToken" text NOT NULL,
    "accessTokenExpires" timestamp,
    "created" timestamp NOT NULL,
    PRIMARY KEY ("id")
);
```

user table:
```sql
-- Sequence and defined type
CREATE SEQUENCE IF NOT EXISTS user_id_seq;

-- Table Definition
CREATE TABLE "public"."user" (
    "id" int4 NOT NULL DEFAULT nextval('user_id_seq'::regclass),
    "name" varchar,
    "email" varchar NOT NULL,
    "image" varchar,
    "created" timestamp NOT NULL,
    PRIMARY KEY ("id")
);
```

session talbe:
```sql
-- Sequence and defined type
CREATE SEQUENCE IF NOT EXISTS session_id_seq;

-- Table Definition
CREATE TABLE "public"."session" (
    "id" int4 NOT NULL DEFAULT nextval('session_id_seq'::regclass),
    "userId" int4 NOT NULL,
    "expires" timestamp NOT NULL,
    "sessionToken" varchar NOT NULL,
    "accessToken" varchar NOT NULL,
    "created" timestamp NOT NULL,
    PRIMARY KEY ("id")
);

```

**Comment by iaincollins** [comment]
> From the structure I see now there are no indexes/fk that have set during initialization of DB data. I'm looking on it there https://github.com/iaincollins/next-auth/blob/master/src/adapters/typeorm/models/account.js. Also should be a good thing to improve

Thanks!

Please note the database schema is in flux and will be until release - in fact the schema has already changed slightly in master, and is likely change in a release that drops in the next few day. The changes are mostly fairly minor; with the exception that email addresses will become optional to support using oAuth providers that don't return them (but you can still choose to enforce providing them if you wish).

There are no change logs until we get to release, so folks using the beta will need to keep an eye on the documentation on each update and understand there will be breaking changes on a regular basis until it is final (there will be official documentation before release!).

To clarify there is no migration script currently, because there is nothing to update to or from as the beta is still pre-release software and breaking changes to the API should still be expected. I was hoping to postpone them till later, but it's less painful to delay the release a bit than to release a breaking update very soon after release.

RE: Indexes / relational mappings

By release, all fields that should have indexes on them should be there on supported databases, however I should add that relational mapping is not planned as the focus is on support for multiple very different backends rather than optimising database metadata for a specific backend.

How to extend and customise models and schemas will be part of the documentation that drops before release though. (This is currently possible, it's just not documented.)

At some point in future dedicated adapters that have more sophisticated support for specific databases might be developed.

**Comment by lnikell** [comment]
Thank you @iaincollins for the reply. Is there any chance before the release that you can consider moving to a more common practice in naming sql tables/fields rather than use JS style.

Usually, for fields name the common practice to use lower_case_underscored names and for tables also lowercase but in plural form.

**Comment by iaincollins** [comment]
I think that's a very reasonable request but have been concerned about adding additional  complexity to the already monkey patched models.

However, it looks like it's possible to [apply a naming strategy](https://github.com/typeorm/typeorm/blob/master/sample/sample12-custom-naming-strategy/naming-strategy/CustomNamingStrategy.ts) with TypeORM and we could do that conditionally (we could even use a [pre-canned model](https://www.npmjs.com/package/typeorm-naming-strategies).

**Comment by iaincollins** [comment]
Note: You can already use the `namingStrategy` option in TypeORM with NextAuth.js, but I don't know how well it will work in practice.

You can track this is #245.

If there are any other feature requests, please create them as a new issue.

**Comment by iaincollins** [comment]
Update for anyone following this issue - Request for Comment on DB schema changes at #254
