### ISSUE TITLE
Support Provider Session Changes

### ISSUE THREAD

**Issue by adarnon** [iaincollins/next-auth#252]
**Summary of proposed feature**
Right now, it is possible to attach additional properties to the Session object by overriding the `session.get` option. This feature can be used to join data from other tables in the database.
If the session is attached to the global context using the `Provider` component under the main App, it is impossible to change it later.
Therefore, if the underlying value of the property changes, there is no way to force a re-fetch of the Session object from the server. The object in the client will be stale.

**Purpose of proposed feature**
There should be some way to demand a session re-fetch. For example, the `useSession` hook could return a function that would trigger a re-fetch if called.

**Comment by iaincollins** [comment]
Thanks for raising this issue! I fully support improving this behaviour.

The version 1 client had a max age for how long session data could be stale on the client, with a default of something like 30 or 60 seconds (but could be set to 0 to force it to never be cached); having something akin to this following the state-while-revalidate pragma is a direction I think makes sense.

The [useSWR](https://swr.now.sh/) hook is a great example of something that does this already, and supports other features like state synchronisation across windows/tabs, and suspense, which feel like related features we'd want to have (I assume it does sync using the localStorage event hack).

As it's not technically possible to extend a React Hook (AFAIK; this seems to be a limitation of Hooks) I would love to lift and shift relevant features into the `useSession` hook. 

_Note: I appreciate we could just tell people to use `useSWR('/api/auth/session')` but actually requiring people to install a separate module is a little kludgy._

**Comment by iaincollins** [comment]
In Pull Request #294 window / tab syncing and the option to set [a max age for client data ](https://next-auth.js.org/configuration/options#client-max-age)(before it auto-updates in the background) is set which should address the issues raised in this PR.

Requiring an env var to set the client max age is somewhat unconventional, but is the least awkward way to set something like this globally across an application, especially one that may of multiple different routes and given there are multiple ways to get the session object.

Checking sessions frequently may have cost implications.

The client max age probably most useful in applications where a short session expiry time is necessary but you also want to avoid sessions timing out due to lack of interaction - or when the client max age is set to a long-ish value (e.g. 15 minutes or more) as away of tracking active users.

It is an advanced option and I suspect most cases is not needed as any time `getSession()` is called changes will now propagate to any components using the `useSession()` Hook (using the new window / tab syncing system), so calling  `getSession()` should be enough and is the recommended way to trigger updating session state manually when using the  `useSession()` Hook.
