### ISSUE TITLE
Customize provider sign-in and callback routes

### ISSUE THREAD

**Issue by botv** [iaincollins/next-auth#259]
**Your question**
Is there a way to customize provider sign-in and callback routes?

**What are you trying to do**
Instead of having users log in at `/api/auth/signin/github`, I'm hoping to have the redirect at `/api/auth/github`, and then the callback at `/api/auth/github/callback`. Is there a way to configure that in the options, or is that something I'd have to set up manually with redirects from those routes?

**Comment by iaincollins** [comment]
That's something you'd need to setup manually for yourself if you want to do it.

The routes are the way they are because we support multiple of providers with as consistent and predictable behaviour, as possible.

Unless NextAuth.js uses paths with specific prefixes like `{prefix}/signup/{provider}` and `{prefix}/callback/{provider}` there is no way to prevent provider routes from clashing with paths reserved for other behaviour.

This is fixed behaviour isn't something we'd look to provide as an option, as it is still possible to do this for anyone that wants to but would add complexity to code and to the product (and to the over all support overhead).
