### ISSUE TITLE
Refresh token for Google provider

### ISSUE THREAD

**Issue by StefanWerW** [iaincollins/next-auth#269]
**Describe the bug**
I have logged the google provider auth, and it never responds with the refresh token.

I have tried using params.access_type: "offline", but no luck.

**To Reproduce**
Simply use the google provider, like in the docs

**Expected behavior**
Have the refresh token in the response, and then in the JWT payload

**Comment by iaincollins** [comment]
You should have the RefreshToken in the [JWT and Signin callback](https://next-auth.js.org/configuration/callbacks), but there is a catch…

What is tricky with Google - and this comes up a lot - is that they only return it the very first time you sign in. I've run into this a bunch and [have written it up on Stack Overflow](https://stackoverflow.com/questions/21942290/passport-node-js-not-returning-refresh-token/44507130).

_tl;dr to get it again, you have to remove the app from your account in Google, or change the request you make to Google to force it to resend it (which triggers an additional authorisation prompt on every sign in)._

The answer provides a couple of ways to fix this and the caveats!

Mostly it's an issue that just impacts developers (while they are testing). A consequence of this is you can use JWT sessions but for Google you still need a database to store their Account details and their RefreshToken as they don't re-issue it on every signin (e.g. unlike Twitter).

**Comment by iaincollins** [comment]
I'm closing this but please do re-open it if the problem you are seeing is something else!

**Comment by StefanWerW** [comment]
@iaincollins Thanks for the response.

I have a work around based on this [post](https://stackoverflow.com/questions/10827920/not-receiving-google-oauth-refresh-token), that is to include the `access_type=offline` and prompt=consent` params.

Which led me to 2 new questions:

1. Why when I use the `params` object it does not work? I was forced to pass in the `authorizationUrl` options.

![image](https://user-images.githubusercontent.com/12717998/84811335-ff725300-b00c-11ea-846d-8b3eb9a8bc90.png)

2.

**Comment by iaincollins** [comment]
> 1. Why when I use the params object it does not work? I was forced to pass in the authorizationUrl options.

The `params` option only apply to Access Token requests made via HTTP POST.

The option name we use was inherited from the one used in `node-oauth`. We have since monkey patched the call, but the option name has remained the same in providers (as it was done in a backwards compatible way).

We should probably change the name at some point (e.g. `accessTokenParams`) or provide an option to more fully customise the post request to allow for dynamic values, and possibly do away with it entirely, but perhaps not until we refactor the OAuth callback code so we can do it in a backwards compatible way and allow time for deprecation for those using custom providers.

> 2. Why are we the wrong url in the google provider. It is documented to use the v2

The Google API docs are inconsistent and it's not clear we are IMO.

IIRC are either 3 or 4 different URLs you can use for some actions and I've not been able to find any notice about which are officially considered deprecated. I suspect, as the OAuth API is [not documented in Google's API explorer](https://developers.google.com/apis-explorer/) that there is no canonical answer to this right now and that different teams in Google have different ideas about what they should be - or perhaps are working towards migrating them all to `oauth2.googleapis.com` but haven't completed that work yet.

Not all the documentation from Google uses the same endpoints - e.g. [Google Play](https://developers.google.com/android-publisher/authorization), [YouTube](https://developers.google.com/youtube/v3/live/guides/auth/server-side-web-apps) and [Video Intelligence](https://cloud.google.com/video-intelligence/docs/common/auth) docs use the same endpoints we are using and in the case of the latter is more recently updated than the OAuth docs.

It may seem reasonable on the surface to use the OAuth docs for guidance, but given it uses odd combination of different hostnames and URL pragmas for versioning I'm not really convinced who ever wrote that doc put much thought into it.

If Google ever canonical list the OAuth 2 endpoints and clarification on what URLs are actually considered deprecated and which are supported, we should update the provider as needed, but in the absence of that I'm not inclined to change it unless there is a practical reason to do so (e.g. some of them stop working or they post a notice saying they intend to retire some of them).

**Comment by elie222** [comment]
Is there a way to do this in Next Auth v5? So that you only request consent when needed?
