### ISSUE TITLE
2.0.0-beta.78 - Next target set to serverless causes [...next-auth] to fail

### ISSUE THREAD

**Issue by Mattsull01** [iaincollins/next-auth#281]
Hey all,

I'm somewhat new to Next and Next-Auth, so I apologize if I'm doing something wrong, or missed something in documentation, but I've done my best to work through this a few times and can't seem to find anything wrong with my setup.  I've also started looking at how Next creates the .next app, but its a lot to take in.

**Describe the bug**
When Next is set to the serverless target in next.config.js, next-auth throws 'no such file or directory, open '/css/index.css''

This issue DOES NOT appear when target: "serverless" is removed.

**To Reproduce**
1. Setup basic Next App (next@9.4.4)
2. Set next.config.js target: "serverless"
3. Setup next-auth / your provider(s), etc. next-auth@2.0.0-beta.78
4. Build Next (I used yarn)
5. Start Next

https://github.com/Mattsull01/next-test

**Screenshots or error logs**
Error: ENOENT: no such file or directory, open '/css/index.css'
    at Object.openSync (fs.js:461:3)
    at Object.readFileSync (fs.js:364:35)
    at Object.<anonymous> (/Users/matt/Code/next-test/.next/serverless/pages/api/auth/[...nextauth].js:176015:1339)
    at Object.zgXW (/Users/matt/Code/next-test/.next/serverless/pages/api/auth/[...nextauth].js:176016:30)
    at __webpack_require__ (/Users/matt/Code/next-test/.next/serverless/pages/api/auth/[...nextauth].js:23:31)
    at Object.tD0P (/Users/matt/Code/next-test/.next/serverless/pages/api/auth/[...nextauth].js:153125:832)
    at __webpack_require__ (/Users/matt/Code/next-test/.next/serverless/pages/api/auth/[...nextauth].js:23:31)
    at Object.vwd5 (/Users/matt/Code/next-test/.next/serverless/pages/api/auth/[...nextauth].js:165619:18)
    at __webpack_require__ (/Users/matt/Code/next-test/.next/serverless/pages/api/auth/[...nextauth].js:23:31)
    at Module.mQn/ (/Users/matt/Code/next-test/.next/serverless/pages/api/auth/[...nextauth].js:128628:67) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/css/index.css'
}

**Comment by iaincollins** [comment]
Thanks for the detailed bug report!

This is an issue with Next.js I've run into this issue myself using node modules and it's frustrating.

I actually didn't realise it was still an unresolved issue.

I think these are some relevant bug reports; I think some of them may have workarounds:

* https://github.com/vercel/next.js/issues/8251
* https://github.com/vercel/next.js/pull/8334

I think the issue is Next.js doesn't detect when a file is loaded using `readFile()`, so any file that loads text files, CSS files, etc in this way fails. For some reason it isn't a problem for Next.js apps deployed on Vercel if the target is not serverless; I don't understand why though.

In the case of NextAuth.js, it is triggered when the build-in pages try to load the built CSS file, which is processed with PostCSS at build time when the module is published, so is pre-minified, etc.

It's technically simple for us to work around; we could just included the built CSS into a css.js file and require that file - instead of reading a CSS file dynamically using `readFile()`.

This is slightly alkward as it means we can't as easily use PostCSS to automatically process the output, at least without a bit work on the build process, so I'll leave this open in case anyone who is familiar with this issue, or who wants to dig into it, is able to suggest an alternative approach we could take.

**Comment by iaincollins** [comment]
This should be resolved now.

I wrote a hacky build script in #297 to wrap the CSS in a JavaScript function as part of the build process, as I couldn't find a good plugin for PostCSS to do this automatically.

Only a limited amount of CSS is used in NextAuth.js - for the built in pages - so I don't think this approach will give us too much trouble to maintain in future, even if it is a bit hacky.

Would love feedback on if this resolved the issue as anticipated.

**Comment by Mattsull01** [comment]
@iaincollins Thanks so much! I'll test it and get back to you with in the next day or so.

~ Matt

**Comment by Mattsull01** [comment]
@iaincollins It solved the issue! Thanks again!

**Comment by iaincollins** [comment]
Hey @Mattsull01 I ran into this today and _I think_ it answers why this wasn't an issue on Vercel.

https://github.com/vercel/next.js/pull/11861

It seems they are using `target: "experimental-serverless-trace"` under the hod on Vercel (instead of `serverless`).

From what I can gather it relies on their own builder, and can be used locally but not sure about being used elsewhere (e.g. to build and run on AWS Lambda). I guess it depends on how the package is built.

It's POSSIBLE we might revert this behaviour in future to make our lives easier, but only if setting "experimental-serverless-trace" actually works for people. If you are still using NextAuth.js down the line interested and able to help test a beta release some time (it should be a simple swap with `npm i next-auth@beta`) please let us know! :-)

**Comment by Mattsull01** [comment]
Hey Iain,

I’m happy to help, let me know when.

Matt
