### ISSUE TITLE
Email flow should not send verification request if user is null. 

### ISSUE THREAD

**Issue by michaelmerrill** [iaincollins/next-auth#356]
**Describe the bug**
Returning `null` from `getUserByEmail` still calls `createVerificationRequest`. If the user is not found in the `getUserByEmail` method, a user should be directed to the error page with a message saying the user does not exist.

Seems like we should check `profile` for being `null` [here](https://github.com/iaincollins/next-auth/blob/19ed684a52a38cf8b56b88451b07a7cede266598/src/server/routes/signin.js#L57) and redirect the user to the error screen with an error like `InvalidEmail`. 

**To Reproduce**
```(javascript)
async function getUserByEmail(email) {
    _debug('getUserByEmail', email);

    if (!email) {
        return Promise.resolve(null);
    }
}
```

**Expected behavior**
Do not try and verify email when a user is not found. Also respond to the user with a message letting them know the email is invalid.

**Additional context**
We could also wrap the getUserByEmail call in a try/catch and request the method throw an error if the user does not exist and redirect from there.

**Comment by michaelmerrill** [comment]
Thinking about it more, maybe this shouldn't be treated as an error. It'd be nice if we could keep the user on the signin page and display a message like "Invalid email".

**Comment by iaincollins** [comment]
So, this happens by design.

1. When an account doesn't exist, a verification email is still generated.
2. When that request is generated a new user account is created for them.
3. The same user account is used the next time the user signs in.

This is the same sign up behaviour that applies to signing in with an OAuth provider.

To stop a user signing in unless they have an account already, the `signin()` callback can be used.

RE: Error handling

I plan to improve the error handling so that some of the errors are displayed on the sign in page when using the built in pages, but at the moment, to do this you need to use custom sign in / error pages.
