### ISSUE TITLE
Yarn found 275 vulnerabilities

### ISSUE THREAD

**Issue by PxT00** [iaincollins/next-auth#394]
**Describe the bug**
Yarn detected 275 vulnerabilities

**To Reproduce**
Run `yarn audit `on master

**Expected behavior**
0 vulnerabilities

**Screenshots or error logs**

![image](https://user-images.githubusercontent.com/65025260/86607173-52da2000-bf7f-11ea-9f63-dfd75b79da35.png)

**Additional context**
n/a

**Documentation feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
If you want to raise a PR to update `package.json` for a specific package to address a known issue, please feel free to do that, otherwise it will be handled as part of regular maintenance - this is mostly automated already (PRs are automatically raised to fix issues once fixes become available).

I appreciate the time taken to raise the issue, but raising a general issue about minor updates that upstream packages don't have fixes for yet is not actionable. I am happy to do to to address specific known issues or even more general issues that are not low priority.
