### ISSUE TITLE
Undesirable 92KB Bundle Size Increase at v1.11.0

### ISSUE THREAD

**Issue by curran** [iaincollins/next-auth#43]
I'm experiencing a bundle size increase of 92KB after upgrading from v1.10.0 to v1.11.0.

I suspect this is due to the [addition of Babel-Polyfill](https://github.com/iaincollins/next-auth/commit/e83c77f6de8027ec78fea8b6463b4e202b5d1640), which [adds all of core-js and regenerator-runtime](https://github.com/zloirock/core-js#babelpolyfill) to the bundle.

Before upgrading my main.js bundle was 213KB, and after upgrading it is 305KB, an increase of 43%.

I am of the opinion that opting into polyfills for IE support should be done at the app level, rather than the library level. In my own case, I have next-auth as a dependency, and would rather not include the babel-polyfill code in my code's bundle, and also would rather not take on `babel-polyfill`, `core-js`, and `regenerator-runtime` as transitive dependencies. My app has no intention of supporting IE, and I'm trying to keep the bundle as small as possible, so I personally would rather not include these polyfills. I'm sure others would also take issue with the inclusion of these polyfills.

The change made in v1.11.0 makes it impossible to opt out of including these polyfills.

Would you kindly consider removing `babel-polyfill` as a dependency of this library, and instead encourage your users who need IE support to add it to their app's codebase instead? Thank you very much.

**Comment by iaincollins** [comment]
Hello! Thanks for raising a ticket, I was going to raise one about this myself. I regard the bloat as a problem as well and want to address it in a future version.

Some options:

* We don't need all of babel-polyfill, and we can (and should) cherry pick the features we actually need. If we could get this down to ~5-10KB I am probably not going to lose sleep over that, but I agree ~100KB is excessive. This is likely the first step as it's probably the quickest and easiest thing to do.

* We could maybe distribute two versions of the client (and leave the default without IE support). If we did this, we would need to make sure that tree shaking works, so that only the version you are using actually gets bundled to the clients (and not both, which would just make things worse).

* As you suggest we could try pushing the dependancy to those using next-auth, with instructions on what to do to include babel-polyfill. I agree this is preferable in principle, however I am not sure how we would do this as IIRC to work I *think* it needs to be included when the module is built.

**Comment by curran** [comment]
Regarding injecting the polyfills at the app level, I believe the order of execution depends on the order of imports, so if the app code imports `babel-polyfill` before it imports `next-auth`, the mutated polyfill globals should be there in the environment by the time any of the `next-auth` code runs. See related Rollup discussion https://github.com/rollup/rollup/issues/1459

I also sort of like the idea of distributing two versions of the client. Maybe it could just be another entry point to the library, looking something like this:

```
import { NextAuth } from 'next-auth/client/withPolyfills'
```

**Comment by curran** [comment]
AFIAK if an app imports `babel-polyfill` before importing `next-auth`, the polyfills will work correctly. This could be the recommended approach for apps that need IE support and depend on `next-auth`. They do not need to be inside the Rollup bundle for `next-auth`.

**Comment by iaincollins** [comment]
Just bumping to say I still plan to investigate this issue. I was just addressing some pressing issues and PRs which had been open for a while, but am going to try addressing this now.

**Comment by masone** [comment]
Importing `next-auth/client` results in a 
```
Error: only one instance of babel-polyfill is allowed
```

for us. I assume it's because we handle polyfilling ourselves in our custom webpack config already. Any advice on how I can proceed?

**Comment by hipstersmoothie** [comment]
I am also getting the error @masone is getting. I'm not doing anything special but my app wont build unless is remove `next-auth/client`.

Here is the repo

https://github.com/hipstersmoothie/kikbak.tv/

**Comment by LoriKarikari** [comment]
v2 is out now and v1 isn't supported anymore.
