### ISSUE TITLE
Does NextAuth store any state on the server?

### ISSUE THREAD

**Issue by mingyeungs** [iaincollins/next-auth#436]
*Please refer to the [documentation](https://next-auth.js.org/getting-started/introduction), the [example project](https://github.com/iaincollins/next-auth-example) and existing issues before creating a new issue.*

**Your question**

Does NextAuth store any state (session / token / etc) on the server (hence making the server stateful?)

1. when using SQLite as database (should be "yes" for this option as it creates a SQLite instance in memory?)
2. when using MySQL/MariaDB/...
3. when using no database

**What are you trying to do**

I want to know whether (or when) the library works on serverless environments (e.g. vercel), or under a horizontal scaling group (e.g. Azure webapp / elastic beanstalk).

Deeper down the question is "how does session work in NextAuth" (assuming it is **server-side session**?). 
Does the server save it in memory? in a SQLite instance? 
or are there actually no session, but a logic that compare JWT with a SALT?

**Documentation feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by zenflow** [comment]
@mingyeungs 

> Does NextAuth store any state on the server?

I am pretty sure the answer is no, unless you count possible caching, so I would think this is safe for a serverless environment. The tagline is afterall "Authentication for Next.js & Serverless".

Regarding where the session data is persisted: The documentation seems to imply that the session data is persisted in your choice of database **and or** JWT. You can choose database only, or you can choose JWT only, or you can choose database+JWT.

Regarding SQLite: This is [from the v3-beta documentation](https://next-auth-docs-git-v3.iaincollins.vercel.app/configuration/databases#sqlite):

> SQLite is intended only for development / testing and not for production use.

So just don't try to use SQLite as your production database and your app will work fine in serverless environment.

**Comment by mingyeungs** [comment]
Thanks @zenflow , I know how silly it must have sounded, and thanks for the confirmation.

Somehow I was under the assumption that `session` means `server-side session`, and was wondering why the library uses session with JWT; Though if `session` simply means `user session`, I guess the question no longer exists...

Anyway I might just leave this question open until getting a confirmation from the library author? Thanks a lot!

**Comment by iaincollins** [comment]
Hi there! Thanks for answering @mingyeungs!

# RE: State

I can confirm NextAuth.js is stateless.

It does take advantage of persistence in a Lambda Serverless function to re-use database connection handlers (and handles re-establishing dropped connections when a function is suspended etc) but it doesn't depend on them and doesn't need a database.

It is designed to work well with Serverless (Vercel, AWS Lambda) and Docker containers / horizontal scaling groups / etc. with and without a database.

The example repo uses `SQLite` as the database, which is a bit of a hack just to support the simple demo site. It is good enough for a demo Serverless instance to use to support email sign in for a demo (as on a low traffic site you are only ever hitting 1 concurrent instance of a function and they stay memory resident for a couple of hours) but that is really just to support the demo site and should not really use SQLite with Serverless on a production site.

You shouldn't use SQLite at all with NextAuth.js, unless you are using it to avoid the need to run an SQL database locally or when running tests.

# RE: Sessions

Yes the situation is a little confusing, I'm trying to improve that in the v3 docs, with the FAQ that @zenflow linked to!

* If using database sessions, the Session Token is a random value used as a key in the database, that is used to look up a user ID and populate the session object returned from `/api/auth/session`.
* If using JWT sessions, the Session Token is a JWT and the data for the session object returned from `/api/auth/session` is  read directly from the token instead of looking it up from a database.
* The contents of the 'session' object is what the client (browser) sees as the session object. You can add properties to the session object with the session callback.

**Comment by iaincollins** [comment]
I think this should be answered now, but feel free to follow up if not.
