### ISSUE TITLE
Why does NextAuth re-render children whenever browser regains focus?

### ISSUE THREAD

**Issue by ghoshnirmalya** [iaincollins/next-auth#454]
**Your question**
Why is NextAuth re-rendering all my components when my browser is regaining focus. See the gif below:

![Kapture 2020-07-20 at 23 03 00](https://user-images.githubusercontent.com/6391763/87968226-b4e96800-cadd-11ea-8e75-ba02c1bd793a.gif)

**What are you trying to do**
NextAuth shouldn't re-render all the children components every time the browser regains focus. Below is a screenshot where the NextAuth wrapper is selected in Chrome devtools:

<img width="1679" alt="Screenshot 2020-07-20 at 11 04 32 PM" src="https://user-images.githubusercontent.com/6391763/87968287-cd598280-cadd-11ea-97fc-f2bd7e1f528c.png">

**Documentation feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
Session state in v3 is updated if a window regains focus (along with some other events). If content is wrapped in a provider this will trigger a re-render depending on how you have structured your page and created your components.

A change in session state is also propagated (using events) to other windows for the site to ensure all tabs/windows are in sync and that a user does not appear to be 'signed in' when they are actually signed out (e.g. after a session has expired).

This is very much by design. SWR from Vercel has a similar functionality.

If you would like this behaviour to be optional when using the `<Provider>`, please do raise a feature request explaining the scenario and the rationale so we can understand how to approach creating an option for this and communicating it clearly in a way that would work for you and other users.

On the surface of it, I don't see why we couldn't provide an option to disable this feature if there was demand for it, though I'm not inclined to change the default behaviour in this case.

**Comment by ghoshnirmalya** [comment]
@iaincollins Thank you for your reply. I wanted to understand more about why this design was done. Thank you for clarifying that.

**Comment by iaincollins** [comment]
@ghoshnirmalya Thanks for asking!

It's always very useful to have questions that are very clear like this as it helps highlighting what we need to do a better job of and to question assumptions about default behaviour (both what is obvious and not obvious, as well as what is good or not good default behaviour!).

**Comment by ticholNyler** [comment]
@iaincollins has anyone else asked for this feature request? We have an application that has video players iframed in and it makes it very tricky to control the behavior.

**Comment by dev-arvilmena** [comment]
@iaincollins hello! I can see that the refetching on window refocus is the default option. But that makes me wonder how are you guys dealing with the local state of the children components getting lost due to these re-render? For example, form values of uncontrolled forms. I also have a nested "modal" system using custom hook similar to [react-hooks-use-modal](https://www.npmjs.com/package/react-hooks-use-modal) implementation, whose child modals disappears when refocusing the window because the open/close local state loses due to re-render.
Are you guys using a state management framework like Redux?
