### ISSUE TITLE
Why is callbackUrl stored in a cookie?

### ISSUE THREAD

**Issue by dramirez42** [iaincollins/next-auth#483]
**Your question**
Hello! I'm having a hard time understand the workflow around callbackUrl. Perhaps you could explain this some more

**What are you trying to do**
I'm trying redirect users to a protected landing page after signing in (`/app/welcome` for example). I seem to be able to control this using the "site" config option, however it gets added to a "next-auth.callback-url" cookie. Which doesn't work great for my use case as it means that if I were to change the location of this landing page (say for example I now want users to get sent to `/app/welcomev2`), users would still get the old page until the cookie gets cleared.

Am I misunderstanding the intent of the callback url?

Thanks!

**Documentation feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [ ] Found the documentation helpful
* [x] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [ ] Found the example project helpful
* [ ] Did not find the example project helpful

**Comment by iaincollins** [comment]
Great question! A cookie is used because not all Providers support tracking the URL the user came from and we want to return them to the page they started their authentication flow once they are signed in. NextAuth.js can be used without a database so we don't really have the option of storing it securely anywhere else.

You can provide the `callbackUrl` either as an option to the `signIn()` or `signOut()` client functions or as a form parameter when signing in. Any value specified should override the previous value.

Before redirecting (and also when saving the URL to the cookie) the `redirect()` callback is called. You can take advantage of this to change where the user ends up by returning a different URL from the callback, so that if they have a different cookie value saved you can ignore it and tell the system to redirect them somewhere else. This callback also prevents bad actors from injecting malicious values that point to other sites.
