### ISSUE TITLE
why provider returns only static attributes such as id,name,email?

### ISSUE THREAD

**Issue by pantchox** [iaincollins/next-auth#60]
Hi,

as the title asks away, its not obvious why can't i set the attributes that are returns from "getProfile" function in the "next-auth.providers.js" file.

its very limiting, what if i want the user profile pic and extra info?
in my twitter provider i set the return object to have extra fields i am interested in but they are never get to the "...this.props.session.user" prop.

how can this be resolved?

thank you!

**Comment by iaincollins** [comment]
Hi there,

You can actually return any properties you like in `getProfile()` in `next-auth.providers.js`.

The reason each provider has this function is that the properties are just different for each provider as annoyingly they all use different names for properties rather than using a standard format for a user object, which is why it doesn't save all properties automatically.

In `next-auth.functions.js` you would need to make sure you use this field in `update()` and `insert()` functions and return it from the `deseralize()` function.

This is quite fiddly and not easy to understand and I'd like to improve this so that the configuration is much simpler in future but I haven't found the time to get around to that recently.

**Comment by pantchox** [comment]
alright now that makes sense, thanks for the clarification!

**Comment by stelian87** [comment]
Hello,
regarding this question i have managed it on my own(sadly before reading this issue):
insert: (user, oAuthProfile) => {
        return new Promise((resolve, reject) => {
          if (!user.photo && oAuthProfile.photos)
            user.photo = oAuthProfile.photos[0].value;

          if (!user.emailVerified && oAuthProfile.emails)
            user.emailVerified = oAuthProfile.emails[0].verified;

          usersCollection.insert(user, (err, response) => {
            if (err) return reject(err);

            // Mongo Client automatically adds an id to an inserted object, but
            // if using a work-a-like we may need to add it from the response.
            if (!user._id && response._id) user._id = response._id;

            return resolve(user);
          });
        });
      }
....

i have a question for @iaincollins if i may.
What is the best approach for getting additional info from a different source? let's say a web api and adding to the user prop.
Scenario: based on email i want to send a request to a web api and return the role, and pass it to the user in the insert.
