### ISSUE TITLE
Documentation: CSRF in headers?

### ISSUE THREAD

**Issue by markschellhas** [iaincollins/next-auth#91]
Hi there,
I'm having trouble finding documentation on using CSRF in headers, for DELETE requests for example.
Where can I find this?

Also, is there documentation for next-auth server-side functions related to getting session values in express server routes, for example?

Thnx

**Comment by KotamanMeOplo** [comment]
I think that for the CSRF you can add a header
'X-CSRF-TOKEN': your token

or in the body of the request (if it has a body) have a property _csrf with the token.
You might need to have the request as a 'application/x-www-form-urlencoded' instead of 'application/json'.
However I am not sure if this is correct or safe.

**Comment by markschellhas** [comment]
@KotamanMeOplo Thanks, that seemed to work ;)
